# Applications
applications/mod_commands
applications/mod_conference
applications/mod_db
applications/mod_dptools
applications/mod_expr
applications/mod_fifo
applications/mod_hash
applications/mod_httapi
applications/mod_spandsp
applications/mod_valet_parking
applications/mod_voicemail

# Codecs
codecs/mod_g723_1
codecs/mod_g729
codecs/mod_opus

# Databases
databases/mod_pgsql

# Dialplans
dialplans/mod_dialplan_xml

# Endpoints
endpoints/mod_loopback
endpoints/mod_sofia

# Event Handlers
event_handlers/mod_cdr_csv
event_handlers/mod_event_socket

# Formats
formats/mod_local_stream
formats/mod_native_file
formats/mod_sndfile
formats/mod_tone_stream

# Languages
languages/mod_lua

# Loggers
loggers/mod_console
loggers/mod_logfile

# Say
say/mod_say_en

# XML
xml_int/mod_xml_rpc
xml_int/mod_xml_curl